Made more changes to the test scripts. Enabled the script run_test_3 during "make check".

diff --git a/test/bin/jpcod b/test/bin/jpcod
--- a/test/bin/jpcod
+++ b/test/bin/jpcod
@@ -7,19 +7,11 @@
 
 init()
 {
-#	CMDDIR=`dirname $0`
-#	CMDDIR=`parsepathname $CMDDIR`
-#	ABSCMDDIR=`absdirname $0`
-#	if [ "$ABSCMDDIR" != "$CMDDIR" ]; then
-#		echo "ERROR: MUST USE ABSOULTE PATHNAME"
-#		exit 1
-#	fi
-#	CMDDIR=$ABSCMDDIR
 	CMDDIR=$(dirname "$0") || return 1
 	CMDDIR=$(realpath "$CMDDIR") || return 1
 	ABSCMDDIR="$CMDDIR"
 	TMPDIR=$(make_tmp_dir jpcod) || return 1
-	HOSTNAME=`hostname`
+#	HOSTNAME=`hostname`
 
 	JAVA=/usr/java/jre1.5.0_07/bin/java
 
@@ -28,47 +20,52 @@ init()
 	KAKADUTOPDIR=$ALTTOPDIR/kakadu-5.2.2
 	JJ2KVER=5.1
 	JJ2KTOPDIR=$ALTTOPDIR/jj2000-$JJ2KVER
-#	LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KAKADUTOPDIR
-#	export LD_LIBRARY_PATH
+	#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KAKADUTOPDIR
+	#export LD_LIBRARY_PATH
 
-	case $HOSTNAME in
-	localhost*)
-		HOSTNAME=ondelette
-		;;
-	esac
+	ALTIMGDIR="$HOME/data/jpeg2000_images/pnm"
+	VMTOPDIR="$HOME/work/vm90/VM9.0"
+	#EXEEXT=".exe"
+	SHOWIMG="display -geometry 256x256> -geometry +0+0"
 
-	case $HOSTNAME in
-	aurora)
-		ALTIMGDIR=$HOME/data/jpeg2000_images/pnm
-		;;
-	ondelette*)
-		ALTIMGDIR=$HOME/data/jpeg2000_images
-		;;
-	vortex*)
-		ALTIMGDIR=d:/users/mdadams/images
-		;;
-	*)
-		echo "ERROR: UNKNOWN HOST $HOSTNAME"
-		exit 1
-		;;
-	esac
+#	case $HOSTNAME in
+#	localhost*)
+#		HOSTNAME=ondelette
+#		;;
+#	esac
 
-	case $HOSTNAME in
-	aurora)
-		VMTOPDIR=$HOME/work/vm90/VM9.0
-		;;
-	ondelette*)
-		VMTOPDIR=$HOME/work/vm90/VM9.0
-		;;
-	vortex*)
-		VMTOPDIR=/
-		EXEEXT=".exe"
-		;;
-	*)
-		echo "ERROR: UNKNOWN HOST $HOSTNAME"
-		exit 1
-		;;
-	esac
+#	case $HOSTNAME in
+#	aurora)
+#		ALTIMGDIR=$HOME/data/jpeg2000_images/pnm
+#		;;
+#	ondelette*)
+#		ALTIMGDIR=$HOME/data/jpeg2000_images
+#		;;
+#	vortex*)
+#		ALTIMGDIR=d:/users/mdadams/images
+#		;;
+#	*)
+#		echo "ERROR: UNKNOWN HOST $HOSTNAME"
+#		exit 1
+#		;;
+#	esac
+
+#	case $HOSTNAME in
+#	aurora)
+#		VMTOPDIR=$HOME/work/vm90/VM9.0
+#		;;
+#	ondelette*)
+#		VMTOPDIR=$HOME/work/vm90/VM9.0
+#		;;
+#	vortex*)
+#		VMTOPDIR=/
+#		EXEEXT=".exe"
+#		;;
+#	*)
+#		echo "ERROR: UNKNOWN HOST $HOSTNAME"
+#		exit 1
+#		;;
+#	esac
 
 	#IMGDIR=$JASPERTOPDIR/data/images
 	#JASPER=$JASPERTOPDIR/src/appl/jasper$EXEEXT
@@ -85,21 +82,25 @@ init()
 	VMENC=$VMTOPDIR/bin/vm9_compress_32$EXEEXT
 	VMDEC=$VMTOPDIR/bin/vm9_expand_32$EXEEXT
 	JJCOD=$CMDDIR/jj2k
-	IMGPATH="$IMGDIR ${IMGDIR}2 $ALTIMGDIR"
+	IMGPATH="$IMGDIR:${IMGDIR}2:$ALTIMGDIR"
 
-	case $HOSTNAME in
-	aurora)
-		SHOWIMG="display -geometry 256x256> -geometry +0+0"
-		;;
-	ondelette*)
-		SHOWIMG="display -geometry 256x256> -geometry +0+0"
-		;;
-	sisley*)
-		SHOWIMG=xv
-		;;
-	esac
+#	case $HOSTNAME in
+#	aurora)
+#		SHOWIMG="display -geometry 256x256> -geometry +0+0"
+#		;;
+#	ondelette*)
+#		SHOWIMG="display -geometry 256x256> -geometry +0+0"
+#		;;
+#	sisley*)
+#		SHOWIMG=xv
+#		;;
+#	esac
 
 }
+
+################################################################################
+#
+################################################################################
 
 parsepathname()
 {
@@ -402,64 +403,9 @@ filename()
 	' -
 }
 
-################################################################################
-# Image characteristics.
-################################################################################
-
-imgwhich()
+to_upper()
 {
-(
-#	DIRS=`echo "$IMGPATH" | tr ':' ' '`
-	for DIR in $IMGPATH; do
-		BUF=$DIR/$1
-		if [ -f $BUF ]; then
-			echo $BUF
-			exit 0
-		fi
-	done
-	echo $1
-)
-}
-
-imgfmt()
-{
-	$IMGINFO < $1 2> /dev/null | awk '{print $1}'
-}
-
-imgcmpts()
-{
-	$IMGINFO < $1 2> /dev/null | awk '{print $2}'
-}
-
-imgwidth()
-{
-	$IMGINFO < $1 2> /dev/null | awk '{print $3}'
-}
-
-imgheight()
-{
-	$IMGINFO < $1 2> /dev/null | awk '{print $4}'
-}
-
-imgdepth()
-{
-	$IMGINFO < $1 2> /dev/null | awk '{print $5}'
-}
-
-imgtype()
-{
-(
-	[ $# -eq 1 ] || exit 1
-	NUMCMPTS=`imgcmpts $1`
-	if [ -z "$NUMCMPTS" ]; then
-		exit 1
-	fi
-	if [ $NUMCMPTS -eq 3 ]; then
-		echo "rgb"
-	else
-		echo "gray"
-	fi
-)
+	tr '[:lower:]' '[:upper:]'
 }
 
 ################################################################################
@@ -482,9 +428,4 @@ ppmtorgb()
 	mv $TMPDIR/ppmtorgb_tmp.grn $GRNOUTFILE
 	mv $TMPDIR/ppmtorgb_tmp.blu $BLUOUTFILE
 )
-}
-
-to_upper()
-{
-	tr '[:lower:]' '[:upper:]'
 }
diff --git a/test/bin/run_test b/test/bin/run_test
--- a/test/bin/run_test
+++ b/test/bin/run_test
@@ -10,6 +10,9 @@ tmp_dir=$(make_tmp_dir)
 
 init
 
+export IMGINFO_COMMAND="$abs_top_builddir/src/appl/imginfo"
+IMGCMP="$abs_top_builddir/src/appl/imgcmp"
+
 DOSHOWIMG=0
 MKDATA=1
 #DATADIR=/tmp/mdadams/jpeg2000
@@ -96,6 +99,23 @@ gettestids()
 	}
 	'
 }
+
+################################################################################
+#
+################################################################################
+
+IMAGE_PATH="$IMGPATH"
+
+while getopts I: opt; do
+	case $opt in
+	I)
+		IMAGE_PATH="$IMAGE_PATH:$OPTARG";;
+	\?)
+		usage
+		break;;
+	esac
+done
+shift `expr $OPTIND - 1`
 
 ################################################################################
 #
@@ -262,7 +282,8 @@ if [ $TSTID != $TESTID ]; then
 fi
 
 	if [ ! -f $INFILE ]; then
-		INFILE=`imgwhich $INFILE`
+		INFILE=$(image_which "$IMAGE_PATH" "$INFILE") || \
+		  panic "cannot find image"
 	fi
 	if [ ! -f $INFILE ]; then
 		if [ $NOIMGWARN -ne 0 ]; then
@@ -286,17 +307,23 @@ fi
 		DECOPTS="$DECOPTS debug=$DEBUG"
 	fi
 
-	IMGDATA=`$IMGINFO -f $INFILE 2> /dev/null`
-	if [ $? -ne 0 ]; then
-		echo "ERROR: cannot get image information for $INFILE"
-		exit 1
-	fi
-	IMGFMT=`echo $IMGDATA | awk '{print $1}'`
-	IMGNUMCMPTS=`echo $IMGDATA | awk '{print $2}'`
-	IMGWIDTH=`echo $IMGDATA | awk '{print $3}'`
-	IMGHEIGHT=`echo $IMGDATA | awk '{print $4}'`
-	IMGPREC=`echo $IMGDATA | awk '{print $5}'`
-	IMGRAWSIZE=`echo $IMGDATA | awk '{print $6}'`
+#	IMGDATA=$(image_info "$INFILE"  2> /dev/null)
+#	if [ $? -ne 0 ]; then
+#		echo "ERROR: cannot get image information for $INFILE"
+#		exit 1
+#	fi
+	IMGFMT=$(image_info "$INFILE" format) || \
+	  panic "cannot get image format"
+	IMGNUMCMPTS=$(image_info "$INFILE" num_components) || \
+	  panic "cannot get number of image components"
+	IMGWIDTH=$(image_info "$INFILE" width) || \
+	  panic "cannot get image width"
+	IMGHEIGHT=$(image_info "$INFILE" height) || \
+	  panic "cannot get image height"
+	IMGPREC=$(image_info "$INFILE" depth) || \
+	  panic "cannot get image depth"
+	IMGRAWSIZE=$(image_info "$INFILE" size) || \
+	  panic "cannot get image size"
 
 	if [ $IMGFMT = mif -o $IMGFMT = jpc -o $IMGFMT = jp2 -o $IMGFMT = pgx ]; then
 		DECFMT=$IMGFMT
