More changes.

diff --git a/test/bin/run_test_2 b/test/bin/run_test_2
--- a/test/bin/run_test_2
+++ b/test/bin/run_test_2
@@ -9,6 +9,7 @@ debug_level="${JAS_DEBUG_LEVEL:-0}"
 if [ "$debug_level" -ge 1 ]; then
 	set -xv
 fi
+set -xv
 
 ################################################################################
 
@@ -100,6 +101,7 @@ for in_file_base in "${in_files[@]}"; do
 	fi
 
 	for image_format in "${image_formats[@]}"; do
+		test_case="$in_file_base-$image_format"
 		echo "############################################################"
 		in_file=$(image_which "$image_path" "$in_file_base") || \
 		  panic "cannot find image $in_file_base"
@@ -135,17 +137,24 @@ for in_file_base in "${in_files[@]}"; do
 		"$jasper" "${enc_opts[@]}" | \
 		  "$jasper" "${dec_opts[@]}" > "$tmp_file"
 		pae=$("$imgcmp" -f "$in_file" -F "$tmp_file" -m pae --max \
-		  2> /dev/null) || pae=
-		if [ -z "$pae" ]; then
-			echo "cannot compare image files $in_file and $tmp_file"
+		  2> /dev/null)
+		status=$?
+		if [ "$status" -ne 0 ]; then
+			echo "imgcmp failed ($status) for $in_file and $tmp_file"
 			error_count=$((error_count + 1))
-			failed_tests+=("$in_file_base-$image_format")
+			failed_tests+=("$test_case")
+			continue
+		fi
+		if [ -z "$pae" ]; then
+			echo "imgcmp output empty $in_file and $tmp_file"
+			error_count=$((error_count + 1))
+			failed_tests+=("$test_case")
 			continue
 		fi
 		if [ "$pae" != 0 ]; then
 			echo "ERROR: $image_format $in_file_base NOT LOSSLESS (PAE=$pae)"
 			error_count=$((error_count + 1))
-			failed_tests+=("$in_file_base-$image_format")
+			failed_tests+=("$test_case")
 			#"$jiv" $tmp_file $in_file
 		fi
 		echo "STATUS: OK"
