imgcmp Program: Added the quiet (-q) and debug-level (--debug-level) options to the imgcmp program.  Also, fixed a memory leak that can occur when the program terminates due to an error.
imginfo Program:
Added the quiet (-q) option to the imginfo program.

JPC/JP2 Codec:
Added some more calls for log message generation.

PGX Codec:
Fixed an apparent bug in the parsing of the PGX header.

Testing Scripts:
Revised the run_test_4 script (which is used for conformance testing).

diff --git a/test/bin/run_test_4 b/test/bin/run_test_4
--- a/test/bin/run_test_4
+++ b/test/bin/run_test_4
@@ -26,9 +26,18 @@ tmp_dir=$(make_tmp_dir "$cmd_name") || panic "cannot make temporary directory"
 debug_level="${JAS_DEBUG_LEVEL:-0}"
 verbose=0
 jas_jp2k_test_top_dir="$JAS_JP2K_TEST_TOP_DIR"
+testcases=()
+enable_imginfo_tests=1
+enable_jasper_tests=1
 
-while getopts T:D:v opt; do
+while getopts T:D:vt:JI opt; do
 	case $opt in
+	J)
+		enable_jasper_tests=0;;
+	I)
+		enable_imginfo_tests=0;;
+	t)
+		testcases+=("$OPTARG");;
 	T)
 		jas_jp2k_test_top_dir="$OPTARG";;
 	D)
@@ -56,99 +65,263 @@ imginfo="$abs_top_builddir/src/app/imginfo"
 export IMGINFO_COMMAND="$imginfo"
 jasper="$abs_top_builddir/src/app/jasper"
 
-
 testcase_file="$cmd_dir/decoder_tests"
-tcf_gettestids "$testcase_file" testcases || \
-  panic "cannot get test cases"
-echo "Number of test cases: ${#testcases[@]}"
-
-error_count=0
-
-for testcase in "${testcases[@]}"; do
-
-	echo "############################################################"
-	echo "Test case: $testcase"
-
-	tcf_gettest "$testcase_file" "$testcase" record || \
-	  panic "cannot get test case"
-
-	enc_file="$JAS_JP2K_TEST_TOP_DIR/${record[encoded_file]}"
-	if [ "$debug_level" -ge 1 ]; then
-		imginfo_opts+=(--debug-level "$debug_level")
-	fi
-	if [ "$verbose" -ge 1 ]; then
-		echo "Running $imginfo ${imginfo_opts[@]} < $enc_file"
-	fi
-	"$imginfo" "${imginfo_opts[@]}" < "$enc_file"
-	status=$?
-	if [ "$status" -ne 0 ]; then
-		echo "error: cannot decode $enc_file"
-		error_count=$((error_count + 1))
-	fi
-
-done
-
-if [ "$error_count" -ne 0 ]; then
-	echo "error count: $error_count"
-	exit 1
+if [ "${#testcases[@]}" -eq 0 ]; then
+	tcf_gettestids "$testcase_file" testcases || \
+	  panic "cannot get test cases"
 fi
 
-exit 0
+skipped_testcases=()
 
-for testcase in "${testcases[@]}"; do
+# Disable test cases that are known to be problematic.
+if [ 1 -ne 0 ]; then
+	tmp_testcases=("${testcases[@]}")
+	testcases=()
+	for testcase in "${tmp_testcases[@]}"; do
+		skip=0
+		case "$testcase" in
+		j2kc_c0p0_13*)
+			skip=1;;
+		j2kc_c1p0_13*)
+			skip=1;;
+		j2kc_c0p0_08*)
+			skip=1;;
+		j2kc_c1p0_08*)
+			skip=1;;
+		esac
+		if [ "$skip" -eq 0 ]; then
+			testcases+=("$testcase")
+		else
+			skipped_testcases+=("$testcase")
+			echo "SKIPPING: $testcase"
+		fi
+	done
+fi
 
-	echo "############################################################"
-	echo "Test case: $testcase"
+echo "Number of test cases: ${#testcases[@]}"
 
-	tcf_gettest "$testcase_file" "$testcase" record || \
-	  panic "cannot get test case"
+failed_testcases=()
+passed_testcases=()
+
+################################################################################
+#
+################################################################################
+
+if [ "$enable_imginfo_tests" -ne 0 ]; then
+
+	cat <<- EOF
+	############################################################
+	imginfo test cases
+	############################################################
+	EOF
+
+	for testcase in "${testcases[@]}"; do
+
+		echo "############################################################"
+		echo "Test case: $testcase"
+
+		tcf_gettest "$testcase_file" "$testcase" record || \
+		  panic "cannot get test case"
+
+		enc_file="$JAS_JP2K_TEST_TOP_DIR/${record[encoded_file]}"
+		if [ "$debug_level" -ge 1 ]; then
+			imginfo_opts+=(--debug-level "$debug_level")
+		fi
+		if [ "$verbose" -ge 1 ]; then
+			echo "Running $imginfo -q ${imginfo_opts[@]} < $enc_file"
+		fi
+		"$imginfo" -q "${imginfo_opts[@]}" < "$enc_file"
+		status=$?
+		if [ "$status" -ne 0 ]; then
+			echo "error: cannot decode $enc_file"
+			failed_testcases+=("$testcase")
+		fi
+
+		passed_testcases+=("$testcase")
+
+	done
+fi
+
+################################################################################
+#
+################################################################################
+
+if [ "$enable_jasper_tests" -ne 0 ]; then
+
+	cat <<- EOF
+	############################################################
+	jasper test cases
+	############################################################
+	EOF
+
+	for testcase in "${testcases[@]}"; do
+
+		if [ "$verbose" -ge 1 ]; then
+			echo "############################################################"
+			echo "Test case: $testcase"
+		fi
+
+		tcf_gettest "$testcase_file" "$testcase" record || \
+		  panic "cannot get test case"
 
 #	for key in "${!record[@]}"; do
 #		echo "$key -> ${record[$key]}"
 #	done
 
-	enc_file="$JAS_JP2K_TEST_TOP_DIR/${record[encoded_file]}"
-	orig_file="$JAS_JP2K_TEST_TOP_DIR/${record[decoded_file]}"
-	dec_file="$tmp_dir/decoded"
-	dec_opts=()
-	if [ "$debug_level" -ge 1 ]; then
-		dec_opts+=(debug="$debug_level")
-	fi
-	if [ "$verbose" -ne 0 ]; then
-		dec_opts+=(verbose=1)
-	fi
-	width=$(image_info "$enc_file" width) || panic "cannot get image width"
-	height=$(image_info "$enc_file" height) || panic "cannot get image height"
-	depth=$(image_info "$enc_file" depth) || panic "cannot get image depth"
-	num_comps=$(image_info "$enc_file" num_components) || \
-	  panic "cannot get number of image components"
-	format=$(image_info "$enc_file" format) || panic "cannot get image format"
-	buffer=$("$imginfo" < "$enc_file")
-	echo "IMAGE INFO width=$width height=$height prec=$depth num_components=$num_comps"
-	echo "IMAGE INFO $buffer"
+		enc_file="$JAS_JP2K_TEST_TOP_DIR/${record[encoded_file]}"
+		orig_file="$JAS_JP2K_TEST_TOP_DIR/${record[decoded_file]}"
+		pae="${record[pae]}"
+		mse="${record[mse]}"
+		comp_no="${record[cmptno]}"
+		dec_file="$tmp_dir/decoded.jp2"
+		orig_pnm_file="$tmp_dir/orig_file.pnm"
+
+		case "$orig_file" in
+		*.tif|*.tiff)
+			tifftopnm "$orig_file" > "$orig_pnm_file" 2> /dev/null || panic
+			orig_file="$orig_pnm_file"
+			;;
+		esac
+
+		dec_opts=()
+		if [ "$debug_level" -ge 1 ]; then
+			dec_opts+=(debug="$debug_level")
+		fi
+		if [ "$verbose" -ne 0 ]; then
+			dec_opts+=(verbose=1)
+		fi
+		width=$(image_info "$enc_file" width) || width=
+		height=$(image_info "$enc_file" height) || height=
+		depth=$(image_info "$enc_file" depth) || depth=
+		num_comps=$(image_info "$enc_file" num_components) || num_comps=
+		format=$(image_info "$enc_file" format) || format=
+		if [ -z "$width" -o -z "$height" -o -z "$depth" -o -z "$num_comps" \
+		  -o -z "$format" ]; then
+			failed_testcases+=("$testcase")
+			echo "SKIPPING: $testcase"
+			echo "$width $height $depth $num_comps $format"
+			continue
+		fi
+
+		if [ "$verbose" -ge 1 ]; then
+			python -c 'print("*" * 80)'
+			cat <<- EOF
+			test case ID: $testcase
+			encoded file: $enc_file
+			reference file: $orig_file
+			decoded file: $dec_file
+			number of components: $num_comps
+			size: $width $height
+			precision: $prec
+			PAE tolerance: $pae
+			MSE tolerance: $mse
+			EOF
+			python -c 'print("*" * 80)'
+		fi
+
+		buffer=$("$imginfo" -q < "$enc_file" 2> /dev/null)
+		#echo "IMAGE INFO width=$width height=$height prec=$depth num_components=$num_comps"
+		#echo "IMAGE INFO $buffer"
 #continue
-	echo "Decoding $enc_file"
+		#echo "Decoding $enc_file"
 #	"$jpdec" software="$dec" input="$enc_file" output="$dec_file" \
 #	  "${dec_opts[@]}"
-	jasper_opts=()
-	jasper_opts+=(-T jp2)
-	echo "Running $jasper ${jasper_opts[@]} < $enc_file > $dec_file"
-	"$jasper" "${jasper_opts[@]}" < "$enc_file" > "$dec_file"
-	status=$?
-	if [ $status -eq 0 ]; then
-		echo "OK"
-		pae=$("$imgcmp" -f "$orig_file" -F "$dec_file" -m pae --max) || panic
-		if [ "$pae" -eq 0 ]; then
-			echo "STATUS: LOSSLESS (PAE=$pae)"
-		else
-			echo "ERROR: PAE CONSTRAINT VIOLATED (PAE=$pae)"
-			#$IMGCMP -f $ORIGFILE -F $OUTFILE -d $DIFFFILE
-			#xloadimage $DIFFFILE > /dev/null
+		jasper_opts=()
+		jasper_opts+=(-T jp2)
+		if [ -n "$comp_no" ]; then
+			jasper_opts+=(--cmptno "$comp_no")
 		fi
-	else
-		echo "ERROR: DECODER FAILED"
-		exit 1
-	fi
-done
+		if [ "$verbose" -ge 1 ]; then
+			echo "RUNNING: $jasper ${jasper_opts[@]} < $enc_file > $dec_file"
+		fi
+		"$jasper" "${jasper_opts[@]}" < "$enc_file" > "$dec_file" 2> /dev/null
+		status=$?
+		if [ $status -eq 0 ]; then
+			if [ "$verbose" -ge 1 ]; then
+				echo "RUNNING: $imgcmp --quiet -f $orig_file -F $dec_file -m pae --max"
+			fi
+			failed=0
+			if [ -n "$pae" ]; then
+				actual_pae=$("$imgcmp" --quiet -f "$orig_file" -F "$dec_file" \
+				  -m pae --max) || actual_pae=
+				if [ -n "$actual_pae" ]; then
+					pae_ok=$(evaluate_expression "$actual_pae <= $pae") || panic
+					if [ "$pae_ok" -eq 0 ]; then
+						failed=1
+						echo "ERROR [$testcase]: PAE constraint violated ($actual_pae > $pae)"
+					else
+						if [ "$verbose" -ge 1 ]; then
+							echo "OK [$testcase]: PAE constraint satisfied ($actual_pae <= $pae)"
+						fi
+					fi
+				else
+					echo "ERROR [$testcase]: PAE check failed"
+					failed=1
+				fi
+			fi
+			if [ -n "$mse" ]; then
+				actual_mse=$("$imgcmp" --quiet -f "$orig_file" -F "$dec_file" \
+				  -m mse --max) || actual_mse=
+				if [ -n "$actual_mse" ]; then
+					mse_ok=$(evaluate_expression "$actual_mse <= $mse") || panic
+					if [ "$mse_ok" -eq 0 ]; then
+						failed=1
+						echo "ERROR [$testcase]: MSE constraint violated ($actual_mse > $mse)"
+					else
+						if [ "$verbose" -ge 1 ]; then
+							echo "OK [$testcase]: MSE constraint satisfied ($actual_mse <= $mse)"
+						fi
+					fi
+				else
+					echo "ERROR [$testcase]: MSE check failed"
+					failed=1
+				fi
+			fi
+			if [ "$failed" -ne 0 ]; then
+				failed_testcases+=("$testcase")
+				echo "ERROR [$testcase]: $testcase failed"
+				continue
+			fi
+		else
+			failed_testcases+=("testcase")
+			echo "ERROR [$testcase]: DECODER FAILED"
+			continue
+			#exit 1
+		fi
 
-exit 0
+		passed_testcases+=("$testcase")
+	done
+fi
+
+################################################################################
+#
+################################################################################
+
+exit_status=0
+if [ "${#failed_testcases[@]}" -ne 0 ]; then
+	exit_status=1
+fi
+
+if [ "${#skipped_testcases[@]}" -ne 0 ]; then
+	echo "The following test cases passed:"
+	for testcase in "${skipped_testcases[@]}"; do
+		echo "    $testcase"
+	done
+fi
+if [ "${#passed_testcases[@]}" -ne 0 ]; then
+	echo "The following test cases passed:"
+	for testcase in "${passed_testcases[@]}"; do
+		echo "    $testcase"
+	done
+fi
+if [ "${#failed_testcases[@]}" -ne 0 ]; then
+	echo "The following test cases failed:"
+	for testcase in "${failed_testcases[@]}"; do
+		echo "    $testcase"
+	done
+fi
+echo "skip count: ${#skipped_testcases[@]}"
+echo "pass count: ${#passed_testcases[@]}"
+echo "fail count: ${#failed_testcases[@]}"
+
+exit "$exit_status"
