Added another simple test script.

diff --git a/test/bin/run_test_2 b/test/bin/run_test_2
--- a/test/bin/run_test_2
+++ b/test/bin/run_test_2
@@ -1,52 +1,78 @@
 #! /bin/bash
 # Copyright (c) 2016 Michael David Adams
 
-CMDDIR=`dirname $0`
-. $CMDDIR/jpcod
-init
+cmd_dir=$(dirname $0) || exit 1
+source "$cmd_dir/utilities" || exit 1
 
-TMPDIR=/tmp/mdadams
+tmp_dir=$(make_tmp_dir)
+tmp_file=$tmp_dir/data
 
-mkdir -p $TMPDIR
-TMPFILE=$TMPDIR/junk.pnm
+abs_top_builddir=$(get_abs_top_builddir) || panic "cannot get top builddir"
 
-INFILES=""
-INFILES="$INFILES target.pnm"
-INFILES="$INFILES stawamuschief.pnm"
-INFILES="$INFILES stawamuschief_gray.pnm"
-INFILES="$INFILES goldenears.bmp"
-#INFILES="$INFILES goldenears_gray.bmp"
-INFILES="$INFILES goldenears.ras"
-INFILES="$INFILES goldenears_gray.ras"
+export IMGINFO_COMMAND="$abs_top_builddir/src/appl/imginfo"
+data_dir="$abs_top_builddir/data"
 
-#FMTS="mif"
-FMTS="bmp jp2 jpc pgx pnm ras"
-#FMTS="$FMTS jpg"
+jasper="$abs_top_builddir/src/appl/jasper"
+imgcmp="$abs_top_builddir/src/appl/imgcmp"
+jiv="$abs_top_builddir/src/appl/jiv"
 
-for INFILE in $INFILES; do
-	INFILE0=$INFILE
-	INFILE=`imgwhich $INFILE`
-	IMGTYPE=`imgtype $INFILE`
-	if [ ! -f $INFILE ]; then
-		echo "WARNING: IMAGE FILE NOT FOUND $INFILE0"
+image_path="$data_dir/images"
+
+in_files=()
+in_files+=(stawamuschief.pnm)
+in_files+=(stawamuschief_gray.pnm)
+in_files+=(goldenears.bmp)
+in_files+=(goldenears.ras)
+in_files+=(goldenears_gray.ras)
+##in_files+=(goldenears_gray.bmp)
+##in_files+=(target.pnm)
+
+image_formats=()
+image_formats+=(bmp)
+image_formats+=(jp2)
+image_formats+=(jpc)
+image_formats+=(pgx)
+image_formats+=(pnm)
+image_formats+=(ras)
+#image_formats+=(mif)
+#image_formats+=(jpg)
+
+error_count=0
+
+for in_file in "${in_files[@]}"; do
+	echo "############################################################"
+	in_file_base="$in_file"
+	in_file=$(image_which "$image_path" "$in_file_base") || \
+	  panic "cannot find image $in_file_base"
+	image_type=$(image_info "$in_file" "type") || \
+	  panic "cannot get image type $in_file"
+	if [ ! -f "$in_file" ]; then
+		echo "warning: cannot find image file $in_file_base"
 		continue
 	fi
-	for FMT in $FMTS; do
-		if [ $IMGTYPE == rgb -a $FMT = pgx ]; then
+	for image_format in "${image_formats[@]}"; do
+		echo "############################################################"
+		if [ "$image_type" = rgb -a "$image_format" = pgx ]; then
+			echo "SKIPPING: $in_file_base $image_format"
 			continue
 		fi
-#		echo "$INFILE0 $FMT"
-		rm -f $TMPFILE
-		$JASPER -f $INFILE -T $FMT 2> /dev/null | \
-		  $JASPER -T $FMT > $TMPFILE 2> /dev/null
-		PAE=`$IMGCMP -f $INFILE -F $TMPFILE -m pae --max 2> /dev/null`
-		if [ "$PAE" != 0 ]; then
-			echo "ERROR: $FMT $INFILE0 NOT LOSSLESS (PAE=$PAE)"
-			$JIV $TMPFILE $INFILE
-#			exit 1
+		echo "TEST CASE: $in_file_base $image_format"
+		rm -f "$tmp_file"
+		"$jasper" -f "$in_file" -T "$image_format" 2> /dev/null | \
+		  "$jasper" -T "$image_format" > "$tmp_file" 2> /dev/null
+		pae=$("$imgcmp" -f "$in_file" -F "$tmp_file" -m pae --max \
+		  2> /dev/null) || \
+		  panic "cannot compare image files $in_file and $tmp_file"
+		if [ "$pae" != 0 ]; then
+			echo "ERROR: $image_format $in_file_base NOT LOSSLESS (PAE=$pae)"
+			error_count=$((error_count + 1))
+			#"$jiv" $tmp_file $in_file
 		fi
-		echo "STATUS: $FMT $INFILE0 OK"
-		#display $TMPFILE
+		echo "STATUS: $in_file_base $image_format OK"
 	done
 done
 
+if [ "$error_count" -gt 0 ]; then
+	echo "error count: $error_count"
+	exit 1
+fi
