Cleaned up the prebuild-v2 script.

diff --git a/build/github/prebuild-v2 b/build/github/prebuild-v2
--- a/build/github/prebuild-v2
+++ b/build/github/prebuild-v2
@@ -56,35 +56,27 @@ if [ -f "$out_file" ]; then
 	rm -f "$out_file" || panic "cannot remove file $out_file"
 fi
 
-dirname=$(dirname "$out_file")
-ls -al "$dirname"
 touch "$out_file" || panic "cannot create file $out_file"
 
 case "$os" in
 linux)
 	;;
-macos-fake)
-	cat >> "$out_file" <<- EOF
-	export PATH=\$(brew --prefix)/opt/findutils/libexec/gnubin:\$PATH
-	EOF
-	;;
 macos)
-	brew install findutils || panic "brew install failed"
+	brew install findutils || panic "cannot install findutils"
 	cat >> "$out_file" <<- EOF
 	export PATH=\$(brew --prefix)/opt/findutils/libexec/gnubin:\$PATH
 	EOF
-	[ $? -eq 0 ] || panic "failed"
+	[ $? -eq 0 ] || panic "cat failed"
 	;;
 windows)
-	# Windows does not like an empty file, apparently.
-	echo "" >> "$out_file" || panic "cannot create file"
-	ls -al "$out_file"
 	;;
 *)
 	panic "invalid OS"
 	;;
 esac
 
-ls -al "$out_file"
+echo "========== start of commands ==========" || panic "echo failed"
+cat "$out_file" || panic "cat failed"
+echo "========== end of commands ==========" || panic "echo failed"
 
 exit 0
