Moved some of the common code in Bash scripts into a single file that is shared between scripts. Replaced a number of different approaches to path canonicalization in various scripts with a single uniform approach. Removed the now obsolete jas_realpath script.

diff --git a/build/build b/build/build
--- a/build/build
+++ b/build/build
@@ -6,7 +6,7 @@
 
 panic()
 {
-	echo "ERROR: $@"
+	echo "FATAL ERROR: $*" 1>& 2
 	exit 1
 }
 
@@ -82,10 +82,14 @@ usage()
 # Early initialization.
 ################################################################################
 
-program_dir=$(dirname "$0") || exit 1
-jas_realpath="$program_dir/jas_realpath"
-abs_program_dir=$("$jas_realpath" "$program_dir") || panic
-sysinfo_program="$program_dir/sysinfo"
+self_dir="$(dirname "$0")" || \
+  panic "cannot get self directory"
+source "$self_dir/base_utilities" || \
+  panic "cannot load base utilities"
+self_dir="$(real_path "$self_dir")" || \
+  panic "cannot get self directory"
+
+sysinfo_program="$self_dir/sysinfo"
 
 ################################################################################
 # Process command line.
@@ -424,7 +428,7 @@ fi
 # Perform some initialization.
 ################################################################################
 
-source_dir="$abs_program_dir/.."
+source_dir="$self_dir/.."
 
 if [ -z "$out_dir" ]; then
 	out_dir="$source_dir/tmp_cmake"
diff --git a/build/build_all b/build/build_all
--- a/build/build_all
+++ b/build/build_all
@@ -2,15 +2,19 @@
 
 panic()
 {
-	echo "ERROR: $@"
+	echo "FATAL ERROR: $*" 1>& 2
 	exit 1
 }
 
-program_dir=$(dirname "$0") || exit 1
-jas_realpath="$program_dir/jas_realpath"
-abs_program_dir=$("$jas_realpath" "$program_dir") || panic
-build_program="$program_dir/build"
-sysinfo_program="$program_dir/sysinfo"
+self_dir="$(dirname "$0")" || \
+  panic "cannot get self directory"
+source "$self_dir/base_utilities" || \
+  panic "cannot load base utilities"
+self_dir="$(real_path "$self_dir")" || \
+  panic "cannot get self directory"
+
+build_program="$self_dir/build"
+sysinfo_program="$self_dir/sysinfo"
 
 list_directory()
 {
@@ -278,7 +282,7 @@ if [ "$debug_level" -ge 1 -a "$verbose" -eq 0 ]; then
 fi
 
 if [ -z "$build_dir" ]; then
-	build_dir="$abs_program_dir/../tmp_cmake"
+	build_dir="$self_dir/../tmp_cmake"
 fi
 
 if [ -n "$command_file" ]; then
diff --git a/build/install_wasmtime b/build/install_wasmtime
--- a/build/install_wasmtime
+++ b/build/install_wasmtime
@@ -8,7 +8,7 @@
 
 panic()
 {
-	echo "ERROR: $*"
+	echo "FATAL ERROR: $*" 1>& 2
 	exit 1
 }
 
diff --git a/build/make_dist b/build/make_dist
--- a/build/make_dist
+++ b/build/make_dist
@@ -2,7 +2,7 @@
 
 panic()
 {
-	echo "FATAL ERROR: $@"
+	echo "FATAL ERROR: $*" 1>& 2
 	exit 1
 }
 
diff --git a/build/make_release b/build/make_release
--- a/build/make_release
+++ b/build/make_release
@@ -4,7 +4,7 @@
 
 panic()
 {
-	echo "ERROR: $*" 1>& 2
+	echo "FATAL ERROR: $*" 1>& 2
 	exit 1
 }
 
@@ -36,7 +36,13 @@ usage()
 
 ################################################################################
 
-self_dir="$(dirname "$0")" || panic
+self_dir="$(dirname "$0")" || \
+  panic "cannot get self directory"
+source "$self_dir/base_utilities" || \
+  panic "cannot load base utilities"
+self_dir="$(real_path "$self_dir")" || \
+  panic "cannot get self directory"
+
 build_wasi_jasper="$self_dir/build_wasi_jasper"
 
 ################################################################################
@@ -83,7 +89,7 @@ if [ -z "$tmp_dir" ]; then
 fi
 
 # Ensure an absolute pathname.
-workspace_dir="$(readlink -f "$workspace_dir")" || \
+workspace_dir="$(real_path "$workspace_dir")" || \
   panic "cannot get absolute pathname"
 
 if [ ! -d "$workspace_dir" ]; then
diff --git a/build/sysinfo b/build/sysinfo
--- a/build/sysinfo
+++ b/build/sysinfo
@@ -2,7 +2,7 @@
 
 panic()
 {
-	echo "ERROR: $@" 1>&2
+	echo "FATAL ERROR: $*" 1>& 2
 	exit 1
 }
 
